# Generated by Django 5.1.4 on 2025-01-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(upload_to='plyrprof')),
                ('contact', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('jersey_number', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
