# Generated by Django 5.1.4 on 2025-01-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=10)),
                ('late_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('player_dtls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app01.player')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_taken', to='app01.staff')),
            ],
        ),
    ]
