# Generated by Django 5.1.4 on 2025-01-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.CharField(max_length=10)),
                ('goals', models.CharField(max_length=10)),
                ('assists', models.CharField(max_length=10)),
                ('saves', models.CharField(max_length=10)),
                ('tackles', models.CharField(max_length=10)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_given', to='app01.staff')),
                ('player_dtls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_records', to='app01.player')),
            ],
        ),
    ]
