# Generated by Django 5.1.4 on 2025-01-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_minutes', models.IntegerField(default=0)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('match_minutes', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0.0)),
                ('training_workload', models.CharField(default='low', max_length=10)),
                ('match_workload', models.CharField(default='low', max_length=10)),
                ('total_workload', models.CharField(default='low', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.player')),
            ],
        ),
    ]
