# Generated by Django 5.1.4 on 2025-01-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_workload'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(choices=[('Session 1', 'Session 1'), ('Session 2', 'Session 2'), ('Session 3', 'Session 3')], max_length=20)),
                ('monday', models.CharField(default='Rest', max_length=50)),
                ('tuesday', models.CharField(default='Rest', max_length=50)),
                ('wednesday', models.CharField(default='Rest', max_length=50)),
                ('thursday', models.CharField(default='Rest', max_length=50)),
                ('friday', models.CharField(default='Rest', max_length=50)),
                ('saturday', models.CharField(default='Rest', max_length=50)),
                ('sunday', models.CharField(default='Rest', max_length=50)),
            ],
        ),
    ]
