# Generated by Django 5.1.4 on 2025-01-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_trainingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=200)),
                ('injury_date', models.DateField()),
                ('out_for', models.CharField(max_length=100)),
                ('recovery_programme', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('player_injured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.player')),
            ],
        ),
    ]
